language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed:v ./udagram-api-feed
  - docker build -t udagram-api-user:v ./udagram-api-user
  - docker build -t udagram-frontend:v ./udagram-frontend
  - docker build -t udagram-reverseproxy:v ./udagram-reverseproxy
  
  #tagging
  - docker tag udagram-api-feed:v dutn1/udagram-api-feed:v2b
  - docker tag udagram-api-user:v dutn1/udagram-api-user:v2b
  - docker tag udagram-frontend:v dutn1/udagram-frontend:v0
  - docker tag udagram-reverseproxy:v dutn1/udagram-reverseproxy:v2b

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - docker login -u dutn1 -p Tiendungcao7777
  - docker push dutn1/udagram-api-feed:v2b
  - docker push dutn1/udagram-api-user:v2b
  - docker push dutn1/udagram-frontend:v0
  - docker push dutn1/udagram-reverseproxy:v2b