version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: udagram-reverseproxy:v4
  api_user:
    build:
      context: ./udagram-api-user
    image: udagram-api-user:v4
  api_feed:
    build:
      context: ./udagram-api-feed
    image: udagram-api-feed:v4
  frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend:v4
